version: '2'
services:
  web:
   build: ./docker/nginx
   ports:
    - "9003:80"
   environment:
    - NGINX_SERVERNAME=flood.dev
   command: /bin/bash -c "envsubst '$$NGINX_SERVERNAME' < /var/www/site.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
   volumes:
          - .:/var/www
   links:
          - php

  php:
    build: ./docker/php-fpm
    volumes:
          - .:/var/www
  db:
      image: mariadb:10
      volumes:
        - ./initdb:/docker-entrypoint-initdb.d
      ports:
        - "3312:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: flood
  testdb:
      image: mariadb:10
      volumes:
        - ./testdb:/docker-entrypoint-initdb.d
      ports:
        - "3313:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: flood